### ISSUE TITLE
Unable to reset room

### ISSUE THREAD

**Issue by Tigarana** [cynicaloptimist/longwave#1]
I really love your longwave project.
I am using a specific room name with my friends, but seem to be unable to reset the room. Players that are leaving the game are still showing up in the room. There is the "..." menu which shows "reset room" when I hover over it, but there is no way to press this and actually reset the room.

**Comment by cynicaloptimist** [comment]
Does this only happen with one specific room, or are you able to reproduce it with a fresh room?

**Comment by fodi** [comment]
I can second that issue, I've just tested it on https://longwave.web.app using latest Firefox and Chromium under Linux, nothing is happening if anyone in the room presses the "..." button. No message appears in the dev console either. Issue seems to be reproducible on fresh rooms every time.

**Comment by cynicaloptimist** [comment]
I can't reproduce this with current Chrome or Firefox. Which browsers and operating systems are you experiencing this with?
