### ISSUE TITLE
[Question] Room code can be influenced by the user

### ISSUE THREAD

**Issue by rfuehrer** [cynicaloptimist/longwave#15]
A four-digit code is generated when rooms are created. Alternative rooms can be opened by specifying a longer code in the URL.

The question is, should only 4-digit rooms be allowed or are longer codes also allowed? When evaluating longer (manual) information, the code must be cleaned up, brought into a desired (valid) format and, if necessary, shortened to the maximum permitted character length.

**Comment by cynicaloptimist** [comment]
This is allowed and intentional.
