### ISSUE TITLE
[Question] Translation patch and hosting

### ISSUE THREAD

**Issue by digaofs** [cynicaloptimist/longwave#20]
Hi,

I've translated the game to pt-br following the readme guidelines, however, due to my lack of skill with github, I'm having a bad time submitting a pull request. Can I send you guys a patch file?
Will you guys enable other languages on the main site or do we need to host our own game in order to use other languages? If so, it's ok to use, let's say, Heroku? Do I need to care about any other dependencies or stuff?

Thanks a lot for the project!

**Comment by digaofs** [comment]
Ok, so I've managed to submit a PR.

The question that remains is about hosting - will the translation be available on https://longwave.web.app ? 

Thanks,

**Comment by cynicaloptimist** [comment]
Thanks for the PR! I'll deploy the localizations to the official site at https://longwave.web.app but there's a bit more work to do before it's ready for prime time.

**Comment by digaofs** [comment]
No problem! Ok, I'll keep waiting, thanks again for the initiative of the project!
