### ISSUE TITLE
Cheating is possible by reading the websocket messages

### ISSUE THREAD

**Issue by ironstep** [cynicaloptimist/longwave#26]
The websocket connection is constantly sending the entire game state to all players, including the correct answer. A player can cheat by looking at the "spectrumTarget" in the received JSON message.

Suggested solution:
The web server should only send a subset of the entire game state to each player and should only provide the "spectrumTarget" to the "clueGiver".

**Comment by cynicaloptimist** [comment]
A more lightweight solution is, don't play with cheaters. I'm not going to
increase the code complexity for this. Thanks for the suggestion!

**Comment by cynicaloptimist** [comment]
Sorry for the terse response earlier. Still, I don't think the tradeoff is worth it; it's a party game and you're probably not playing with random pick-up groups. Thanks for the interest in the project!
