### ISSUE TITLE
two-dimensional version

### ISSUE THREAD

**Issue by piporg** [cynicaloptimist/longwave#3]
Hello there,

we found your awesome game and really enjoy playing it via the internet while being in a video conference.
We thougt about a two-dimensional version of that game, where you have to place your guess in a grid like that:

```
   delicious
       ^
soft <-+-> hard
       Y
  undelicious
```

Maybe that would increase the fun level even more ;)

**Comment by cynicaloptimist** [comment]
Haha, this is a pretty cool idea.
