### ISSUE TITLE
Allow clue giver to pick between two options -- the "front" or "back" of the card

### ISSUE THREAD

**Issue by darthwalsh** [cynicaloptimist/longwave#32]
I think have the option would be more fun for a first-time clue-giver, or if you feel one option isn't appropriate with your group of friends.

From the [rules](https://www.ultraboardgames.com/wavelength/game-rules.php) I think it could work like this:

> Choose a wavelength: Draw 1 wavelength card from the deck. They're double sided, and the Psychic can choose the side they want to use for their clue. On most cards there's a "normal" side and a "weird" side. Don't think too hard about it: just pick the one you find most interesting!
Place the card in the slot in front of the device, with your chosen side facing forward, and read the card text so both teams can hear.

**Comment by OverloadUT** [comment]
Perhaps a half-way version of this feature (that would be quick to implement) could simply be a button that lets you draw a new spectrum and it replaces the old one. Then the group has the option of deciding what they want the rule to be: one redraw allowed, infinite redraws, whatever is right for the group.

**Comment by cynicaloptimist** [comment]
There is a "Draw a different card" feature available in Free Play and Teams modes. I'm not likely to implement any "two-sided cards" though.

**Comment by OverloadUT** [comment]
Oh, I had no idea "draw a different card" was there! Thanks for the tip.
